# Generated by Django 3.1.1 on 2020-09-17 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unsplash', '0002_auto_20200917_0659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='author_created_date',
        ),
    ]
